title: GitHub Repository Showcase
baseurl: "/repo_posts"
url: "https://tom-doerr.github.io"
remote_theme: pages-themes/primer
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
