name: Curate AI Repos and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  curate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run curation script
        working-directory: ./curated_ai
        run: python curate_ai_repos.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add curated_ai/repos.js docs/_posts/*.md
          git commit -m 'chore: auto-curate AI repos and clean posts [skip ci]' || echo "No changes to commit"
          git push

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # Adjust path if your site root is different
          path: ./curated_ai
